//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2PRojekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFirstContext : DbContext
    {
        public ModelFirstContext()
            : base("name=ModelFirstContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bend> Bends { get; set; }
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<Ucestvuje> Ucestvujes { get; set; }
        public virtual DbSet<Zanr> Zanrs { get; set; }
        public virtual DbSet<Muzicar> Muzicars { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<MuzickaIzdavackaKuca> MuzickaIzdavackaKucas { get; set; }
        public virtual DbSet<Koncert> Koncerts { get; set; }
        public virtual DbSet<Menadzer> Menadzers { get; set; }
        public virtual DbSet<Nagrada> Nagradas { get; set; }
        public virtual DbSet<Daje> Dajes { get; set; }
        public virtual DbSet<Osvaja> Osvajas { get; set; }
        public virtual DbSet<Pripada> Pripadas { get; set; }
        public virtual DbSet<Svira> Sviras { get; set; }
        public virtual DbSet<Snima> Snimas { get; set; }
        public virtual DbSet<Izdaje> Izdajes { get; set; }
        public virtual DbSet<Odrzi> Odrzis { get; set; }
    }
}
