//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze2PRojekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osvaja
    {
        public int UcestvujeBendIdBenda { get; set; }
        public int UcestvujeFestivalIdf { get; set; }
        public int DajeFestivalIdF { get; set; }
        public int DajeNagradaIdNag { get; set; }
    
        public virtual Ucestvuje Ucestvuje { get; set; }
        public virtual Daje Daje { get; set; }
    }
}
